### ISSUE TITLE
Adding test images to the repository

### ISSUE THREAD

**Issue by karhohs** [sorgerlab/cycif#2]
Hello,

Would you please add a test image set to this repository? It would be very helpful to have access to test images, so that the scripts in this repository can be tested on the same data these scripts were created to analyze.

Thanks you for considering my request!

**Comment by jrlin1001** [comment]
Hi 

We're working on putting images onto the public repository (Image Data Resource, IDR) now.  However, we're more than happy to share some sample sets first.   Which types of images (plate/cell-based or tissue) are your interested?   

Thanks, 
-Jerry-

**Comment by karhohs** [comment]
Hi Jerry,

Tissue is of greater interest to me. Will you be uploading these images to the repository or IDR?

Thank you!

**Comment by jrlin1001** [comment]
Sorry for the delay.   A set of sample images could be found here:

https://www.dropbox.com/sh/fhn8qbow3qk2lc1/AABOIbSk7JoshSukS33HB1cQa?dl=0

These images could be used as inputs for the scripts provided in here.
